### ISSUE TITLE
Can you please add some output images.

### ISSUE THREAD

**Issue by aAmitSengar** [coderbyte-org/big-o#2]

**Comment by Burnedo** [comment]
@aAmitSengar please define `output images`?

**Comment by aAmitSengar** [comment]
meaning how we can see the result with this library, you have explained the use in vary good way but after implementation how i will see the output i.e 

> O(n)

**Comment by Burnedo** [comment]
@aAmitSengar this library has no GUI,

Result is returned by calling [AnalysisService.analyze method](https://github.com/coderbyte-org/big-o/blob/master/src/AnalysisService.ts#L54) as the [AnalysisResult](https://github.com/coderbyte-org/big-o/blob/master/src/structures/AnalysisResult.ts)
